apiVersion: 1

datasources:
  - name: Chronicle
    uid: Chronicle
    type: prometheus
    access: proxy
    url: http://chronicle:8086
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: "15s"

  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
