apiVersion: v1
kind: Service
metadata:
  name: demo-app-chronicle
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - name: chronicle-http
      port: 8086
      targetPort: 8086
    - name: sidecar-health
      port: 8080
      targetPort: 8080
